[build]
  publish = "."
  command = ""

[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/_ds/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/assets/uploads/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000"
